version: "3.5"

services:
    redis:
        container_name: Redis
        image: "bitnami/redis"
        environment:
          - REDIS_PASSWORD=Three@141592653589793
        ports:
          - "6379:6379"